### ISSUE TITLE
Reschedule Product Haul not show all bins

### ISSUE THREAD

**Issue by awangatsanjel** [Sanjel-Energy-Services/eService_WorkItems#108]
Problem: User can not change the bin for the blend loading to.

Step to reproduce:

1. Schedule product haul on Rig Board blend column.  The rig has more than one bins assigned. Load full amount to only one bin.
2. Reschulde the above product haul.
3. Only the bin with load amount shows up.

Expected behavior:
The initially selected bin should show with the load amount value. Other bins should show up with 0 value. User is allowed to change the values in this bins load amount, just like "Schedule Product Haul" does.

Reschedule Product Haul on Bulk Plant board needs to be double chcked to see if it has same issue.

![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/55812393/955a96b3-449b-496f-8209-9e5dda6492c5)

![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/55812393/31e8cc5d-5556-4a88-95b3-861f1f1be4a2)

**Comment by Alice0610** [comment]
@awangatsanjel  I have retested the bug on Rig Board Blend column and found the bug has been fixed. 
                            On Bulk Plant BIN column, there is no such bug since there is only one specific BIN to reschedule product haul.
                            On Rig Board BIN column, there is no such bug since there is only one specific BIN to reschedule product haul.

**Comment by awangatsanjel** [comment]
@wistaria623
不知道你们是否处理过这个bug，只有 @Alice0610 写了回复，好象是没复现出问题。

以下两种情况会复现：

1. 在Rig Board Blend列 Schedule Product Haul 时，不添写任何Bin Unload Amount，然后Reschedule，所有的BIN 都不显示了。
在Bulk Plant Board BIN列也会出现
2、在任何地方 Schedule Product Haul 时，任何Bin Unload Amount，然后Reschedule，这时候所有Bin能够正常显示，删除已有的Bin Unload Amout，保存。再Schedule，所有的BIN 都不显示了。

其实就是一种情况，当所有BIN都没添Unload Amount，Reschedule时这些BIN都不能显示出来。

**Comment by wistaria623** [comment]
@awangatsanjel 
这个bug之前我们修复的不完全，所有bin为空时，Reschedule 时就有了问题，今天童韬已经修复了这个问题

**Comment by tobeytong** [comment]
@awangatsanjel 
今天我进行这个BUG修复的时候，和李英讨论过
当时我们有两种修改思路
一种是，当用户不填写Bin Unload Amount时，将默认值0存入数据库中
但是我看了代码，在保存的时候，会检查Bin Unload Amount值，小于0.01的不会保存
我担心这样改会影响其他系统

另一种修改是，当如果没有Bin Unload Amount信息时，根据RigId，从BinInformation中拉取对于的BIN信息，然后将其呈现到页面上，使用户在修改的时候可以填写数据，这种修改对原有的数据逻辑没有影响。

目前我们使用了后一种修改，已经将其提交
