### ISSUE TITLE
Rig Board Notes - Tonnage decimal places

### ISSUE THREAD

**Issue by JasonSchneider19** [Sanjel-Energy-Services/eService_WorkItems#120]
Currently in the notes of the rig board, the tonnage has 3 decimal places. Only 1 decimal is required
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/1b803c9b-3888-4803-83d4-8e609d2f1d88)

**Comment by Alice0610** [comment]
@JasonSchneider19  May I know the correct format? I have discussed with my team member and made a conclusion as below. Please check and provide con-currence. If you have furthur concern, please let know immediately.
1862:  0.0t     unknown
1867: 16.0t    surfacemix

**Comment by JasonSchneider19** [comment]
@Alice0610 
This is correct:
1862: 0.0t unknown
1867: 16.0t surfacemix

**Comment by Alice0610** [comment]
@JasonSchneider19 
I still have one question.  Do we need to do same change to descriptions above the bin load amount?
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/131580642/51bd0415-7ffc-4624-9057-7ca00756e86c)

**Comment by JasonSchneider19** [comment]
@Alice0610 
No, other changes are not needed. Cleaning up the look of the main page is all that is requested. 
The above picture is all that is needed.
