### ISSUE TITLE
Bulk Plant Bin - On Location - Shipping Load Sheet not implemented

### ISSUE THREAD

**Issue by awangatsanjel** [Sanjel-Energy-Services/eService_WorkItems#123]
Just found Bulk Plant Bin - On Location - Shipping Load Sheet actually was not implemented.

**Comment by zhangyuan5** [comment]
@awangatsanjel  Bulk Plant Bin列的On Location 操作调用的后台ActionName ： OnLocationShippingLoadSheet。现在代码中并没有该方法的实现，已调整了和Rig Job Bin列的On Location 操作调用的方法一致。
在下面的需求中禁用了OnLocation功能，
[Requirement63: Disable OnLocation function on Rig Board and BulkPlant#130](https://github.com/Sanjel-Energy-Services/eServiceOnline/issues/130)

**Comment by awangatsanjel** [comment]
我忘了前面有这个禁用的需求了。不用改了。
