### ISSUE TITLE
Rig Board Haul Blend menu is disabled

### ISSUE THREAD

**Issue by awangatsanjel** [Sanjel-Energy-Services/eService_WorkItems#130]
Step to reproduce

1. Schedule a blend request on a blend in Rig Board
2. Change the blend request status to "BlendCompleted"

```
update producthaulload set producthaulloadlifestatus = 4 where system_id=xxxx;
```
3. Go to the blend and click "Haul Blend", the blend request shows up, but it is disalbed.

Change:

1. Enable the menu when the blend request is in Scheduled, Blending, BlendCompleted, Stored statuses.

**Comment by tobeytong** [comment]
@awangatsanjel 这个需求的实现如下：

1.找到Rig Board页面组成列表信息的ViewModel   RigJobViewModel,找到组成PREFL,BLEND,DISPL三列的菜单列表的函数SetHaulBlendMenuForBl，在判定菜单"Haul Blend"是否可用时，将判定条件改为判定Blend request的状态，当状态为 Scheduled, Blending, BlendCompleted, Stored时，菜单的状态为可用。

2. 找到与Bulk Plant页面组成列表信息的ViewModel   BulkPlantJobViewModel,找到组成Bin列的菜单列表的函数SetHaulBlendMenuForBin，在判定菜单"Haul Blend"是否可用时，将判定条件改为判定Blend request的状态，当状态为 Scheduled, Blending, BlendCompleted, Stored时，菜单的状态为可用。

**Comment by awangatsanjel** [comment]
@tobeytong 请注意读需求，识别需求的适用范围。你在之前的工作中，出现太多适用范围误别错误，导致代码作废的情况。

这个需求给你描述了具体的重现步骤，已经是一个非常确定的场景。并没有涉及Bulk Plant页面。你多改了Bulk Plant页面，如果用户说不对，又需要改回去。因为它们这两个页面的用户角色是不一样的，所以它们的菜单可用的业务逻辑也是不一致的。
