### ISSUE TITLE
Clear All Button on Rig Board and Bulk Plant

### ISSUE THREAD

**Issue by JasonSchneider19** [Sanjel-Energy-Services/eService_WorkItems#135]
@awangatsanjel 
Currently we have the following on the job board (DRB)
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/3daaf140-f375-4008-8644-59a326ab5d6b)

We have the following on the rig board:
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/de4f7bfe-0bb5-4742-a44c-bf45d0340670)

Would like the clear all on the rig board and bulk plant (once the areas are added
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/a1eacb1c-c0c8-4c6a-978e-cff977bc91d0)

**Comment by awangatsanjel** [comment]
@awangatsanjel Please work on this task today.

It's for both RigBoard and Bulk Plant Board
