### ISSUE TITLE
Haul Blend form bugs

### ISSUE THREAD

**Issue by awangatsanjel** [Sanjel-Energy-Services/eService_WorkItems#158]
Click Haul Blend from Bulk Plant bin, Blend In Bin.

1. Bin name should use Bin Information Name
2. Quantity for existing blend in bin is not rounded to 3 decimal places if the value has more than 3 decimal places.

![HaulBlendFromBulkPlantBIN bug](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/55812393/efca1c2c-e146-4b83-91a5-01f5599fe087)

**Comment by awangatsanjel** [comment]
@wistaria623 @zhangyuan5
Haul Blend From Bulk Plant Bin found new bugs.

1. When the blend in Bin is from a blend request, sometimes it shows the base blend name of the base blend.
![Haul_Blend_In_Bin](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/55812393/dc902bd6-04d0-46ac-9bba-e3999a23c36d)

2. When the blend in Bin is from Adjust Blend Amount, the base blend shows blank. 

![Haul_Blend_In_Bin_2](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/55812393/b51e0434-be2e-41c3-8af3-e3d4a4f9a5bb)

The rules is as following:

1. If the blend description is in  [Base Blend] + [Percetage]% [Additives] format, the [Base Blend] should be selected in the base blend list.
2. If the blend description is in  [Base Blend] only the [Base Blend] should be selected in the base blend list.

The base blend should not looked up based on the recipe.

**Comment by awangatsanjel** [comment]
@wistaria623 @zhangyuan5

今天新加的这个bug，我已经顺手修复了。

**Comment by Alice0610** [comment]
Verified decimal issue on branch 259 and found decimal issue is fixed.
Rig Board Bin:
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/131580642/aabec727-3c2c-4d92-87fd-c62995ab0fb5)


Bulk Plant Bin:
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/131580642/6353b918-7887-4a9d-a678-d3f13599cc21)
