### ISSUE TITLE
Excess import - eProgram

### ISSUE THREAD

**Issue by JasonSchneider19** [Sanjel-Energy-Services/eService_WorkItems#164]
Want to add the cement excess to be imported to eProgram.
This will be a decimal number - require 2 decimal places. Can be > 1.
This value could be from 10.00 to 0.01 (please allow any value)

This value will be available in the following location in the import file:
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/2c54859e-728a-4cf2-bdf4-0a729dd94ece)

Attached is an example import file with 2 excess values in it
[PRG2400374.00.csv](https://github.com/Sanjel-Energy-Services/eService_WorkItems/files/14409439/PRG2400374.00.csv)

**Comment by tobeytong** [comment]
@awangatsanjel  

![Image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/32862704/6869f498-e1f4-4683-a3bf-5ca306d5b2f4)

Hi Adam

我根据CSV文件上传后的情况，大致整理出了这次需要修改的内容，但是不知道是否正确

1. 我找到了这部分的数据的保存表，PRG_TEST_REQUEST_SCTNS，那么我需要在这里增加一个字段保存Excess，是否正确

2. PRG_TEST_REQUEST_SCTNS这部分数据，在CSV文件中，需要有以下五个字段有值才会写入数据库
Base Blend不为空 ，Category不为空，Field Blend Testing为Yes
且所属的Job Type，Job Type ID均为不空
这个推论是否正确

**Comment by awangatsanjel** [comment]
@tobeytong 

1. 不正确。导入数据项的位置已经明确指出它属于BlendSection实体。
2. 因为1不正确，所以都不正确。这只是在原有的导入增加一个数据项，你为什么会搞出那么多逻辑出来？

**Comment by Alice0610** [comment]
@awangatsanjel @JasonSchneider19 @tobeytong 
After review the requirement provided by you, I still have some queries. Please help to figure out my quiries. Thank you in advance.

> This value could be from 10.00 to 0.01 (please allow any value)

- If  the string is boundary  values such as 10.01 and 0.00,  no record will be created in e-Service Sanjeldata. 
- If the string contains special characters such as !@#$%^&, no record will be created in e-Service Sanjeldata.
- If the string is -1, no record will be created in e-Service Sanjeldata.

**Comment by awangatsanjel** [comment]
@Alice0610

We don't handle invalid data exception in eProgram import. This rule is a constraint for the import file and give the information for developer to define data type.  All your rules are valid but we are not to implemented, and also not necessary for testing. You may use the sample file provide by Jason for import testing, only test the valid value, no negative test is needed.

Additionally,

1. The data is not created in SanjelData. As a BA, you should not look into DB level.
2. The data value range description "This value could be from 10.00 to 0.01 (please allow any value)" is clear enough for a developer to work on, and the validation rules should be standard to handle, you should not define it again for every field. 
3. This is a requirement for importing a new filed. It will be the same way imported as other fields. Tong Tao had his analysis earlier, if you talk to him, you might have got answer from him.

@tobeytong @wistaria623 @JasonSchneider19

**Comment by awangatsanjel** [comment]
@Alice0610 为什么移到Blocked列? 但是又没有问题提出来?
