### ISSUE TITLE
Crew assignment not shown on Job Board 

### ISSUE THREAD

**Issue by JasonSchneider19** [Sanjel-Energy-Services/eService_WorkItems#168]
When creating a haul in 2 scenarios, they are not showing up on the Job Board
-	Creating a backhaul
-	Creating a haul from a program

Creating a Backhaul:
Right clicking on the “Bin” (that has cement in it) on the “Rig Board” brings up the option for back haul:
 
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/eac68698-ec61-48fc-b1d2-ca2056551c4d)

In the above example, I right clicked on bin 1928.
The plan is to use David | 746160 for the back haul
 
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/71b14670-cc5b-46c9-a921-9b6c4bc94fbd)

Right clicking on the bin opens up a form and after filling it out:
 
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/e30780b2-3814-42db-bec4-a4f30cf8ecd8)

We can see that David | Julien-Lee | 746160 status automatically went from Off Duty to “Load Requested”:
 
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/96b7faa9-0f52-4c2b-8f4d-0491b4d516a2)

The haul does not show up, which is desired/expected to show up similar to the haul above for llyas|Moustapha|746163.
 When the status’ are set so that the haul has arrived at the location the cement tonnages need to be updated – this is currently working properly:
-	The 15 tonne need to be taken out of bin 1928
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/a58dab51-8ff6-464c-88ea-0fc00d4dba04)

-	The 15 tonne need to be added to silo 3 (selected in the form)
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/7921f54e-ca3c-4e7f-89ef-6b14fd25c3ba)

Haul From Program:
Right clicking on the “Bin” on the Rig Board allows to “Schedule Product Haul”.
Use Scott on the job board: Scott on the Job Board:
 
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/def1086a-82b7-4317-ab4b-0d33dd3593cc)

This will bring up a window as follows:
 
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/c574a110-2960-4e5a-8c5d-b289fc7c3f07)

Fill out the appropriate information:
 
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/56b51018-5da6-4317-ba93-7c59c53df8cb)

Hit Save and expect the haul to show up on the board:
 
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/1723207d-fbc1-4713-bff1-121b08c29c25)

•	Load has been requested, but the haul is not visible
Once Scott is toggled through the status’ and he is “On Location”, expect that 19.75 tonne is put into silo 1867.
 
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/2844827b-95ac-4d63-9654-319c1eb71106)

Check quantity in the bin:
 
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/3ceb458b-1e00-4e6e-a488-addb8997550b)

•	This is working properly

**Comment by Alice0610** [comment]
Supple the implementation



![Image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/131580642/6427c915-0d7b-436f-8fe8-cd500d1410f3)



![Image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/131580642/254d6a3e-6c64-432f-ba29-c19f81f140bb)



![Image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/131580642/b2a8f182-2b15-49c4-b105-dcfec398533d)

**Comment by zhangyuan5** [comment]
问题原因分析，
现在代码中Producthaul显示的条件是需要和RigJob关联，并且RigJob不能为空，代码见：AssignmentCrews.Razor

![Image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/132034221/516148e1-45f9-4aa0-b90f-394cedcc064f)

而RigJob数据的来源是必须是存在CallSheet，代码见：BulkerAssignmentDataService.cs
![Image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/132034221/0bb71855-e4ad-4115-8bc2-99b86749d465)

在eserviceOnline的Rig Board Blend列创建product Haul时候, ShippingLoadSheet是存在CallSheet和BlendSection的，没有问题。
而在Rig Board Bin列进行创建product Haul或者创建Back Haul时候，ShippingLoadSheet是没有CallSheet的，因此，对于这种情况数据的加载逻辑并不适用。

在Bulker Plant Bin列进行创建Haul Blend时候也是一样的，ShippingLoadSheet是没有CallSheet的，因此，对于这种情况数据的加载逻辑同样不适用。

综上，整个数据的加载逻辑是以RigJob为核心，而Bin列的schedual product Haul和RigJob并没有直接关系，需要修改整个PopulateDataAsync和AddBulkerCrewsDataChangedEventHandlerAsync的数据加载和关联的逻辑。

**Comment by awangatsanjel** [comment]
@Alice0610 @wistaria623 
I don't understand your comments in "Supple the implementation". There lacks of the connections among your screenshots.
