### ISSUE TITLE
Update Crew assignment information on Job Board

### ISSUE THREAD

**Issue by JasonSchneider19** [Sanjel-Energy-Services/eService_WorkItems#169]
•	Use Client Short Name
o	Current view:
 
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/ddddbfe6-b62d-44b1-a0e7-d10974d918e0)

o	Desired view:
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/7dd6e0cb-a75d-4687-bd94-a572d9723a9c)

o	The Rig Board uses the short name
•	Add Icons for haul type
o	Would like the icons added to the Job Board so that the type of haul is known immediately. (each icon to have different shades of blue)
o	Haul 
	🚛 (HTML Code: `&#128667;` )
o	Back haul
	🚚(HTML Code: `&#128666;` )
o	Transfer Haul
	 🔁(HTML Code `&#128472;`)
o	Various combinations of the icons may be required for a single entry on the job board
	If a normal haul is planned with a back haul, both icons will show up.
•	This is only if this has been planned prior to the start of the 1st haul
	If a haul is loaded, and then a 2nd haul, back haul, or transfer is added, this will be added as a 2nd haul. Each haul will only have 1 icon.
•	Look of the information on the Job Board:
o	Currently showing client / rig
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/45aa837f-bf16-447b-8255-23e9864bd521)

o	Desired look when multiple icons are planned:
	Naming will remain the same as current (Client above Rig)
	When multiples, it is to look as follows:
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/2cfbf923-6c91-4759-b2db-bb28f877bf40)

o	For transfers & backhauls, in place of the “Client” will be “Bulk Plant/Rig”. In place of “Rig” will be “Back to Bin”
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/29ea34ac-03a3-405d-91c7-9ed061403ee3)

**Comment by Alice0610** [comment]
@JasonSchneider19  @wistaria623 
I have designed mockup for back haul and transfer haul. Please provide con-currence therefore we could proceed the development. Thank you in advance.

![Image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/131580642/9583595b-3255-4015-9d6b-802cc836ee8b)

**Comment by JasonSchneider19** [comment]
@Alice0610 @wistaria623
Want to make sure that we are focused on using the “Short name” for the client
Eg. Baytex Energy Ltd. = “Baytex”, Meg Energy Corporation = “MEG”. The short names are used on the rig board for reference.
Bulk Plant can just be BP =  “FSJ BP”

Each "block" on the job board to have an originating location and destination location. This is how they will be seperated on the job board

Normal Haul: Leave as is. Client (Short Name) / Rig
•	Icon Color – “Green”
Back Haul: 
•	Originating Location / Destination
•	If the back haul is from Baytex / Savanna 425 and going back to FSJ bulk plant
•	Would like to see Savanna 425 / FSJ BP
•	On hover, show same info as Normal Haul – blend, date and bin
•	Icon Color – “Yellow”
Transfer Haul: 
•	Originating Location / Destination
•	If the transfer haul is from Baytex/Savanna 425 and going back to FSJ bulk plant
•	Would like to see Savanna 425 / FSJ BP
•	If the transfer haul is from Baytex/Savanna 425 and going back to Tourmaline/PD 538
•	Would like to see Savanna 425/ PD 538
•	On hover, show same info as Normal Haul – blend, date and bin
•	Icon Color – “Blue” – leave as is

![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/917ee3c5-5709-4bb6-ba33-b91321582253)

**Comment by Alice0610** [comment]
![Image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/131580642/5c44b89c-20c6-457d-a5b7-ea3ec4f815cc)



![Image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/131580642/9b5ab0a9-115a-4381-a798-66de2727c6a4)



![Image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/131580642/1b29ab8e-1449-49f5-b489-c54e51f87145)



![Image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/131580642/b7a823b6-fde7-4fb4-ab05-5a7f325c05bb)

**Comment by tobeytong** [comment]
根据宝红的review建议，对代码进行优化

**Comment by awangatsanjel** [comment]
@tobeytong @Alice0610 @wistaria623 

在这任务中存在一个bug

有时Program中的客户名字与主数据并不完成全一致，这样通过名字就找不到主数据的记录。

例子：在Rig Bin创建 Product Haul时，使用PRG2200565.00，该客户后来改过名字。这导致Job Board显示ShortName时因为找不到该客户而抛出异常。

如果通过客户名字找不到主记录数据，ShortName使用客户名字中的第一个单词
