### ISSUE TITLE
Thickening Time Import - eProgram

### ISSUE THREAD

**Issue by JasonSchneider19** [Sanjel-Energy-Services/eService_WorkItems#174]
Similar to the excess import, would like to import the Thickening Time.
This needs to be per blend
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/807adfd3-72c9-40cf-8438-66ab0ff1f9e7)
Format will be Hr:min
eg. for one hour thirty minutes:
      1:30 or

This will need to be import but not required to be shown anywhere in eProgram.
It is not editable.
Value will be carried over with the blend to Call sheet and job package
It will be available in the eProgram dataset linked to each cement blend
Attached is a file with 3 thickening times in 2 different job types

[PRG2400454.00.csv](https://github.com/Sanjel-Energy-Services/eService_WorkItems/files/14621034/PRG2400454.00.csv)

**Comment by tobeytong** [comment]
@awangatsanjel  @wistaria623  @belazhbh 
 
在这个任务，新增的字段和上次一样，依然属于BlendSction实体
而且由于需要保存到Call sheet and job package中
所以比Excess做更多的处理



宝红提出，由于这个新增字段是Hr:min格式
所以我们应该使用TimeSpan自行保存，最后转为Long保存到数据库中

**Comment by awangatsanjel** [comment]
@tobeytong @belazhbh @wistaria623 

这又是一个在已有功能上增添的一个字段的导入的需求，没有任何新的业务逻辑需求。不知道你们为什么按出这么多事情？照猫画虎，按着前面已有的实现做就可以了。
1. BlendSection只有Excess没要被带到Call Sheet和Job Package中，其他数据项都被带过去了或有相应的处理。照着做就行了。
2. Hr:min格式也不是新的数据类型，它在TT100min, TT100max等数据导入都使用过，也有现成的方法可循，它代表的是小时和分钟，转换成分钟保存，int类型。

**Comment by Alice0610** [comment]
@awangatsanjel @wistaria623 @tobeytong 
我创建了jobpackage后，并且把这个jobpackage发送到server端后，在数据库里查找不到相应的record。您能否告知我们[PSPT_BLEND_SCTNS]和callsheetnumber是怎么关联的呢？或者是我们业务上哪里还不了解？
programid = PRG2400454.00
callsheetnumber = 1110761
jobpackagenumber = 12345679
