### ISSUE TITLE
Rig Board - Page Selection

### ISSUE THREAD

**Issue by JasonSchneider19** [Sanjel-Energy-Services/eService_WorkItems#186]
On the rig board, we need to scroll to the bottom of the page in order to toggle through the various pages.
The selector is located at the bottom of the page:
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/e5dd61e6-d6fc-4761-847b-bcad3f043358)

Would like to add a second page selector to the top of the page. Keep the one at the bottom, but add a second one at the top. This way a person can change pages whether they are at the top or the bottom of the page

It can look similar to the following:
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/44a09acf-e071-41f6-91d6-944a253efc8d)

**Comment by awangatsanjel** [comment]
@JasonSchneider19 The page selection bar can be added on the top as well, but is won't be the same row with main menu. Let developer to propose where it can be.

**Comment by wistaria623** [comment]
The page selection bar can be added ,UI Mock such as follows:

![Image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/37645176/efe4de99-7baf-4e3c-b06c-002e80c54849)

**Comment by wanghuan69** [comment]
问题1：
复现步骤：页面在第2页，点击上一页按钮
预期结果：首页序号内容显示正确
实际结果：首页序号发生变化，内容未发生变化
说明：页面在第2页，点击首页按钮，也会出现同样情况

问题2：
步骤：当前页为尾页，点击首页按钮，
预期结果：首页序号内容显示正确
实际结果：首页内容空白

**Comment by tongtao17** [comment]
![Image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/169008869/6e07fbb1-61c4-43cb-bdcd-e8d42c7e9a46)

![Image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/169008869/6bd3ca08-1988-471a-8edb-5e34ce013079)


@awangatsanjel 

我发现了一个，当我们选择最后一页的时候，通常都会出现没有数据的空页面

我检查了后台代码，发现我们计算count的时候，用于分页的数据还没有过滤完

我调整了计算count的位置，这样不会再出现分页器上有最后一页，但是跳转后没有数据，而前一页尚没有塞满十八条数据的情况

**Comment by wanghuan69** [comment]
开发分支验证通过
