### ISSUE TITLE
Rig Board - Prejob Teseting

### ISSUE THREAD

**Issue by JasonSchneider19** [Sanjel-Energy-Services/eService_WorkItems#187]
On the rig board, there is a test tube icon that indicates that testing of the cement blend is required.
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/2b39eb1c-8d61-4647-afee-661cde258c4d)
This information comes from the program.
These jobs are important for the operations team to be looking at and following along in the progress of when they are coming up, the status of the blending and what all needs testing to look at the workload of the bulk plants and laboratory.
Would like to see a check box added to the header of the rig board for "Prejob Testing"
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/698f45b3-1f65-4cde-978f-637c09f5ce44)
Once selected, only jobs that require prejob testing would be shown on the page.
Once deselected, all jobs would show up on the page

**Comment by wistaria623** [comment]
On the rig board,
A filter condition is added:Prejob Testing(Check Box)
- Once selected, only jobs that require prejob testing would be shown on the page.
- Once deselected, all jobs would show up on the page

Supports combination with other filtering conditions.
UI Mock such as follows:


![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/698f45b3-1f65-4cde-978f-637c09f5ce44)

**Comment by awangatsanjel** [comment]
@wistaria623 @tobeytong 

在开发员动手前，要确认需求理解正确。在所有描述里根本没有提到BIN，不知道为什么会对BIN想这么多。

“完全没有Testing的RigJob已经过滤掉了”，为什么没有代码提交？

**Comment by wanghuan69** [comment]
开发分支验证通过
