### ISSUE TITLE
Call Sheets - Additional equipment - Add "Type" to the print out

### ISSUE THREAD

**Issue by JasonSchneider19** [Sanjel-Energy-Services/eService_WorkItems#188]
In eService, when creating a call sheet, a plug loading head can be added in the additional equipment.
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/2c08a563-4330-492c-a19f-5943aadad0ca)
Once this is selected: additional information can be added about the plug loading head:
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/bfdb16e3-118d-4cd4-be68-2d22a71db8d8)
The information that is available is as follows:
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/0e6cf86b-00a1-4e0c-85de-8e2580e69b93)
When the information is added, the type is missing from the print out:
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/255f58eb-a3da-44db-b86f-c832002f3e5e)
The print out loos as follows:
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/8aea8147-71b5-4231-a595-fed0351e1dd4)
Desire to have it look as follows:
Plug Loading Head: 36 “ Extended Body 139.7 mm TXP BTC Top Drive Adapter: 114 mm XH
Plug Loading Head: Type Size Thread Type Top Drive Adapter: (if Yes) Size Thread Type

**Comment by awangatsanjel** [comment]
Architech Notes:

The call sheet printing was not updated when I added PlugLoadingHeadSpecialty. This only needs to change PlugLoadingHeadSectionPrintHelper.cs to add the the PlugLoadingHeadSpecialty's description to the front.

USA part doesn't need to be updated. We don't have USA anymore.

**Comment by wistaria623** [comment]
Eservice callsheet print update:
Additional  Equipment - Plug Loading Head section,Print content format:

Current situation:
Plug Loading Head: 【Size】 【Thread Type】 Top Drive Adapter: (if Yes) 【Size 】【Thread Type】

Update target:
Plug Loading Head: 【**Type** 】【Size】 【Thread Type】 Top Drive Adapter: (if Yes) 【Size 】【Thread Type】

**Comment by awangatsanjel** [comment]
Code is fixed.
