### ISSUE TITLE
eService Online - Allow rescheduling product haul before OnLocation status

### ISSUE THREAD

**Issue by JasonSchneider19** [Sanjel-Energy-Services/eService_WorkItems#191]
Ability to “Reschedule” a haul up until the status is changed to “On location”
If the status is scheduled, called, loading, loaded, Enroute or anything else prior to On Location, it can be rescheduled
This will send a workflow notification
The MTS will be updated
The call sheet will be updated
Dispatch will phone the team members as required to ensure changes are known
The auto offload function will continue to work as designed

**Comment by awangatsanjel** [comment]
Architect Notes:

Beyond current implementation of rescheduling product haul. We will just allow the product haul being rescheduled when the product haul process is In Progress.

**Comment by wistaria623** [comment]
Product haul can be Rescheduled if one of the following states:

- Scheduled
- InProgress
- Loaded
- Loading

**Comment by wistaria623** [comment]
@JasonSchneider19 
When I was testing, I found that the returned state of Product haul can also be Rescheduled.
I don't think that's right.
So the returned state should not be allowed to be modified, right?

![Image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/37645176/89c1f853-5d5b-4e22-a32b-4213c3be7b37)

**Comment by awangatsanjel** [comment]
@wistaria623
Returned and OnLocation status don't allow rescheduling. Just fix it.
 You have clarified the 4 product haul statuses which allow rescheding in your previous comments.

**Comment by wanghuan69** [comment]
开发分支验证通过
