### ISSUE TITLE
Add "Revert Approval" button to allow manager re-approve job package

### ISSUE THREAD

**Issue by awangatsanjel** [Sanjel-Energy-Services/eService_WorkItems#27]
There are so many request for pushing job back to awaiting for approval by field managers. It will be good to implement this process to let them handle it by them self.

Adding a button under "Job Package From Server" tab, permission is only granted to field managers. It only reset the approval status as same as our database script doing today.

**Comment by cgaine** [comment]
Should we put a disclaimer message when clicking this button?  Specifically, I'm thinking about what will update from an integration perspective.  ie.. Variable Pay will but Service Ticket to AX will not.  Score integration?

**Comment by awangatsanjel** [comment]
Once the job package is re-approved, all integrations will be triggered again.  This is our manual support process now, and we don't see issue so far. 
Viktor, please comment.
