### ISSUE TITLE
Tab Order - Plug loading head

### ISSUE THREAD

**Issue by JasonSchneider19** [Sanjel-Energy-Services/eService_WorkItems#62]
The tab (on the tough books tab is used as primary way to move around) order in the plug loading head seems to be random

![image](https://user-images.githubusercontent.com/95711838/211874065-20f89bd4-15de-4dd8-88cf-df1f0cb6b875.png)

Start at supplier, hit tab – goes to thread type.
Go supplier, manufacturer (when possible), type, size, thread type ….left to right

**Comment by Alice0610** [comment]
@JasonSchneider19  
I have checked in UAT and found the tab order in UAT is displayed the same as that in production. May I know your preference for the tab order displayed on plug loading head?


![Image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/131580642/5bb011e4-fb95-4925-a701-caec950fef85)

**Comment by Alice0610** [comment]
@JasonSchneider19  I have ajusted the tab order on tough books. Please do review and raise concern if there is.

 

![Image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/131580642/71249e7f-6615-4afb-bc1f-bd655143daac)

**Comment by JasonSchneider19** [comment]
@Alice0610 
This looks good, please move forward
