### ISSUE TITLE
Supervisor - Prevent removal of units in eService

### ISSUE THREAD

**Issue by JasonSchneider19** [Sanjel-Energy-Services/eService_WorkItems#65]
Access to prevent supervisors from removing any units from eService. The units are used by groups for various pieces of data.
If they need to be fixed, a manager can repair the data entry.
"We use the unit number on the ticket to track the number of loads, I have noticed that some supervisors delete units (for some unknown reason). I would like to remove this option for them. The hauls are already completed, there is no reason to change at that point." - Colin Fraser.

**Comment by Alice0610** [comment]
@JasonSchneider19 
I  have checked in Sanjel e-Service and only find one place where supervisor can be able to delete units. Please provide confirmation if it is ok to disable the DELETE button for supervisor?



![Image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/131580642/31e1b40a-5d8d-48d7-a128-adaa8714b4e4)

**Comment by JasonSchneider19** [comment]
@Alice0610 
yes please. That is the only place that i see it as well.

**Comment by Alice0610** [comment]
@JasonSchneider19 I have checked in Sanjel e-Service and found that Clear All button can also remove all records at one time. Do we need to disable the button too?
@ZhangYuan

![Image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/131580642/5258a1db-5c54-412a-b6f1-6e3f32682e7c)

**Comment by Alice0610** [comment]
@JasonSchneider19 
Zhang Yuan and I have checked in system and found Remove units button in 3 places. We have disabled the button in scenario1 and scenario 2. Please double check in production if Remove units button could be disabled in previous 2 scenarios.
1. Main page || Click on a concrete Call Sheet || Expand the call sheet || Click on Units and Personnel 
2. Tasks || Update Call Sheet || Click on Next || Click on Units and Personnel 
3. Tasks || Create Call Sheet || Click on Next || Click on Units and Personnel

**Comment by JasonSchneider19** [comment]
Updating and creating call sheet should be able to edit and remove all

**Comment by Alice0610** [comment]
@JasonSchneider19 
We have done implementation based on our communication.
As I observed in system, field supervisor only has access to View Call Sheet. Therefore, we have disbaled REMOVE and CLEAR ALL in View Call Sheet. 
Meanwhile, Administrator can not be able to  REMOVE or CLEAR ALL on the section of View Call Sheet. However, Administrator is still able to do REMOVE and CLEAR ALL action on Create Call Sheet and Update Call Sheet.
If you have furthur concern, please let me know immediately.

**Comment by Alice0610** [comment]
@JasonSchneider19 @zhangyuan5
I have below queries for unit&personnel update in Sanjel e-Service.

- Login the system with identity Field Supervisor
![Image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/131580642/fa86f416-c685-444f-81ff-c8b0510ca311)

![Image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/131580642/27b50ece-5579-401a-8536-9b9ab6c50924)

**Comment by JasonSchneider19** [comment]
@Alice0610 
The field supervisor should not have access to the Clear All or Remove button is any screen
All call sheets from server, job packages from local, job packages awaiting approval or job packages from server - field supervisor cannot clear all or remove units
Field supervisor can only edit

**Comment by Alice0610** [comment]
@JasonSchneider19 

Based on communication today, supervisor should not have access to REMOVE or CLEAR ALL on the section of Update Call Sheet, View Call Sheet, Update Job Package from Local job, View Job Package from Local Job, Update Job Packages from Server.

**Comment by JasonSchneider19** [comment]
@Alice0610 
Yes, correct : Based on communication today, **_field_** supervisor should not have access to REMOVE or CLEAR ALL on the section of Update Call Sheet, View Call Sheet, Update Job Package from Local job, View Job Package from Local Job, Update Job Packages from Server.

**Comment by Alice0610** [comment]
@JasonSchneider19 
Did you receive confirmation from Chris for Administrator's access?

**Comment by JasonSchneider19** [comment]
@Alice0610 
Sorry for the delay, yes i have confirmation - we are only concerned about the Field Supervisor

**Comment by Alice0610** [comment]
@JasonSchneider19 
Okay. We will not disable Administrator's access to unit on any screen.

**Comment by JasonSchneider19** [comment]
@Alice0610 
Thank you
