### ISSUE TITLE
Program Id update

### ISSUE THREAD

**Issue by JasonSchneider19** [Sanjel-Energy-Services/eService_WorkItems#68]
@awangatsanjel 
eProgram & eService Program ID & # Update
The definitions that will be used are as follows:
•	Program #: This is the PRG followed by the 7 digits indicating the number. For example PRG2300836
•	Program Rev: this is the revision number of a program. For example Rev 3
•	Program ID: this will be the Program # joined with the Program Rev/100 added to the end. For example: PRG2300836 Rev 3 will be PRG2300836.03
The Program ID will be available to the data warehouse to be used with Power BI
A program will be imported with both the program # and program rev values. 
The application will need to create the program ID and display it throughout eProgram and eService.
The Program ID will also be used to create a call sheet.
 
eProgram
On the main search page, show Program ID.
Remove Rev
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/f57466e1-dd7d-457f-a256-c77e1592cc46)
At the bottom of the main page, update Program ID for the selected program in the grid:
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/dabad986-2ef8-4954-b5b6-b5b0dacdb553)
On search:
Have the ability to search by either the Program ID or the Program #
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/b93f0161-4ae9-4eab-b7c0-a1a8a3093a64)
For example:
Searching for PRG2102501 would show all programs - PRG2102501.00, PRG2102501.01, PRG2102501.02 etc (will show all programs available) as follows:
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/b460c360-aa57-4a19-88a7-9a990493b155)
Searching for PRG2102501.00 will bring up only PRG2102501.00
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/2dda8a1c-2853-40ac-b120-ec33322f0c14)
In the program header:
Update the Program ID to have the decimal, remove the revision #
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/46ebb4b2-73ce-42b9-977b-381a6592df7c)
eService
Call Sheets:
Update main grid, Call sheets from server to Program ID and remove revision
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/445d3661-ffa2-4342-8b9b-356ed9b7a016)
When creating a call sheet, must allow decimals and when “Input Program ID”:
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/d37f3a9f-face-4d2b-86ba-72762e19be1d)
The decimal is required entry when creating a call sheet.
Previous functionality of selecting a revision will go away – no longer required
On Step 5 of the call sheet creation, update Program ID and remove revision:
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/8930daf4-7afc-494c-b58b-f77d14c0667a)
Call Sheet Print out, update the footer:
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/b2177f11-1f8f-4038-90dd-55e4aeb0db4d)
eService Job Package:
Service Ticket Field Estimate, update footer to Program Id and remove revision (All Pages)
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/c2dd0a22-b652-4150-b99f-d0f73281f806)
Service Ticket District Approved, update footer to Program Id and remove revision (All Pages)
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/e695424a-cf67-4e13-95ad-b3e2b979695d)
Cement Service Report, update footer to Program Id and remove revision (All Pages):
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/35f7040c-9d03-4907-90f2-76b8cd62c892)

**Comment by awangatsanjel** [comment]
Architect Decision: We will keep ProgramId (PRGxxxxxxxx) and ProgramRevision design in code and database no change. All UI and Report will display two values as one string. PRGxxxxxxx.dd.

**Comment by Alice0610** [comment]
@JasonSchneider19 @awangatsanjel
I have one query of the new requirement. Please help to provide solution. Thank you in advance.

- Program ID: this will be the Program # joined with the Program Rev/100 added to the end. For example: PRG2300836 Rev 3 will be PRG2300836.03

  - If the previous revision is NULL in system, can we transfer the value to 0? 0/100 = 0  For example: PRG2300836 Rev 0 = PRG2300836.00
  - If the previous revision is 100 or larger, how should we handle the number? 

![Image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/131580642/3357d9af-1843-4fb2-9bbb-6247237b6e4c)

**Comment by JasonSchneider19** [comment]
@Alice0610 
The revision number will never be larger than 99. 
99 is the max allowed.

**Comment by wistaria623** [comment]
- [ ] [ProgramId update  Program#26](https://github.com/Sanjel-Energy-Services/SanjelClientSolutionTool/issues/26)

- [ ] [ProgramId update eService  #11](https://github.com/Sanjel-Energy-Services/SanjelEService/issues/11)
