### ISSUE TITLE
Fix missing fields in shipping load sheet

### ISSUE THREAD

**Issue by awangatsanjel** [Sanjel-Energy-Services/eService_WorkItems#69]
1. Destination
Shipping load sheet's destination should be the current rig location or bulk plant location. For active rigs, it can be retrieved from the rig job that the product haul is orignated; if or the last job completed on the rig. If the rig job is a special one for Bulk Plant, use its well location. 

Bulk Plant address will be populated in well location field in separate task.

2. ClientName
When a product haul is scheduled, it should have a client associated. The client is normally from the job which the product haul  goes to. If it is an internal product transfer or haul back, the client should be Sanjel.

3. ClientRepresentative
Same as above, the ClientRepresentative can be retrieved from job.

**Comment by Alice0610** [comment]
@awangatsanjel 
I have reviewed the requirement and have below queries, please help to provide solution.

1.Destination:
- In current system, destination will be displayed as empty while shcedule product haul from Bulk Plant
- Bulk Plant -- what kind of rig job can be regarded as a special rig job?

2. ClientName
- Internal Product Transfer or haul back 
  How to diagnose if  a product haul is internal or external?

3. ClientRepresentative
- I can not find the item in datatable Rigjob. Can you figure out the concrete table name?

**Comment by awangatsanjel** [comment]
@Alice0610 
This is a bug fix requirement. You only need to fix it in existing implemented use cases. You cannot do it within the use cases not implemented even if they are mentioned.
All information needs you to find out from related entities. there is no solution can be provided.

ClientRepresentative equals Client Consultant.

**Comment by Alice0610** [comment]
@JasonSchneider19  Can you provide confirmation for below queries today?

1.  How to diagnose if a product haul is a Sanjel one?
     - If it is an internal product transfer or haul back, the client should be Sanjel.

 2. Under what condition can the rig job be regarded as a special one?
     - If the rig job is a special one for Bulk Plant, use its well location.

**Comment by JasonSchneider19** [comment]
@***@***.***>
Yes, I am looking into this and have reached out to Adam for some clarification. I have not heard back yet.
Jason


"We Moved" 
​To
​1600, 530-8 Avenue SW, Calgary, AB T2P 3S8
 
Jason Schneider, P.Eng, P.Chem
Engineer-Applications
 
403-510-6152
 
***@***.***
 
403-269-1420 x 1034
1600, 530 8 Avenue SW
Calgary, AB 
T2P 3S8
sanjel.com
This message contains confidential information and is intended only for the intended recipients. If you are not an intended recipient you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission. If verification is required please request a hard-copy version.

**Comment by awangatsanjel** [comment]
@Alice0610 

1. All rig jobs without call sheet number/call sheet id are special rig jobs, they use rig job mechanism to be shown on Rig Board or Bulk Plant Board. These special jobs may represent bulk plant, down rigs, etc.
2. We haven't implemented product haul back and internal transfer yet.

**Comment by Alice0610** [comment]
@awangatsanjel  I have made a brief summary for current system behavior and will check furthur for rig jobs without call sheet number/call sheet id.

-- Schedule a product haul on Blend Column of Rig Board

   -   Client name is empty
   -   Client Representative is empty
   -   Destination - Rig ID

-- Schedule a product haul on BIN column of Rig Board
   - Client name can bedisplayed normally
   - Client Representative can be displayed normally
   - Destination can be displayed normally

-- Schedule a product haul on Blend column of Bulk Plant
   - Client name can bedisplayed normally
   -  Client Representative is empty
   - Destination - Rig ID
