### ISSUE TITLE
DRB Filtering

### ISSUE THREAD

**Issue by JasonSchneider19** [Sanjel-Energy-Services/eService_WorkItems#73]
Filter the DRB by Main Group - "Operations"
There are a few people missing from the current list - and the filtering is different between DRB and eService. 
Filter them both by the same to remove some people issues.
Use Operations as this will include managers (sometimes used in the winter season) and field engineers which are currently missing.

**Comment by cameliabalan** [comment]
Similar to ticket #117 and will use that one to track the requirement
