### ISSUE TITLE
Area Filtering

### ISSUE THREAD

**Issue by JasonSchneider19** [Sanjel-Energy-Services/eService_WorkItems#81]
@awangatsanjel 

Ops would like the ability to filter the DRB (all pages) by NW, Central, NE and SE
Would like added to the top where the current filters are located:
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/7f328b1c-0311-4730-be30-80e1a3347d79)

N.West = FSJ+GP
CENT = BR+RD+Eds+Edm+NW
       (NW is referring to Norman Wells)
N.East = LLD+LLB
S.East = EST+SC+KD

This is the order that they would like to see them.
Like the following:
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/7df3511e-31dc-448f-8e61-a42188ae22d7)

**Comment by awangatsanjel** [comment]
@JasonSchneider19 I would like to extend this desire to column filter and sorter. When the district filter are combined, it will be harder to find the job within multiple pages on RigBoard.

**Comment by JasonSchneider19** [comment]
Additional details:
1.	When an area checkbox is checked, all service points check boxes are checked automatically.
2.	When an area checkbox is checked off, all service points check boxes are checked off automatically.
3.	When a service point checkbox is checked, the area checkbox which the service point is under is checked automatically.
4.	When a service point checkbox is checked off, the area checkbox which the service point is under will be checked off only when all service points under this area are checked off.
5.	For other scenarios when a service check is checked off, the area checkbox maintains no change.

Layout as following so that are is near service points:
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/ba93f7aa-08ea-44c9-9af2-691547e0e372)

When area is selected, all service points are selected:
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/cacb1cb0-bfdc-42d8-ad79-c4b2e6c3b9d6)

Ability to select additional districts on top of just the area:
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/c5d4cdd2-00e6-4043-afdb-b640ff9259b0)

**Comment by arcurve-cheryl-chan** [comment]
@JasonSchneider19 

1. Could we have the area checkboxes above the service point checkboxes?
2. Can we reorder the service point checkboxes so that the NW checkbox is beside the other Central checkboxes?

@awangatsanjel  Does your comment refer to the RigBoard only?

**Comment by JasonSchneider19** [comment]
@arcurve-cheryl-chan 
Ops is ok with either way.
Just now allowed to slow things down even more....

**Comment by awangatsanjel** [comment]
@arcurve-cheryl-chan That's a good question.
@JasonSchneider19 Is the change on RigBoard only good enough?

**Comment by JasonSchneider19** [comment]
@arcurve-cheryl-chan @awangatsanjel 
I think we need to be consistent across the whole DRB
it will be used on the rig board, job board, and Crew Mgmt pages for sure

**Comment by awangatsanjel** [comment]
@arcurve-cheryl-chan filters will only apply to RigBoard, for  DRB boards the filters were built already.

**Comment by cameliabalan** [comment]
In summary:
1. Add Area checkboxes above the existing District checkboxes: Cent, N.West, S.East, N.East in this order
2. Areas and their districts:
    CENT = BR+RD+Edm+Eds+NW (NW is referring to Norman Wells)
    N.West = GP+ FSJ
    S.East = EST+SC+KD
    N.East = LLD+LLB

4. Position the areas above the first district from that area
5. Re-order the districts to be grouped together under the corresponding area    
    a. move NW (Norman Wells) immediately after Eds (Edson)
6. Selecting one area will automatically select all the districts belonging to that area
7. Selecting all districts in an area will automatically select the corresponding area
8. It should be possible to select an area which will include all districts for that area and then select another district from another area
9. Apply this to all DRB pages as well as Rig Board

**Comment by awangatsanjel** [comment]
@cameliabalan The area selectors should be just a shortcut to allow user select/deselect multiple districts together. The existing district filter logic will not be changed. 
So No.6 is better to be "Selecting any district(s) in an area will automatically select the corresponding area"

**Comment by JasonSchneider19** [comment]
@cameliabalan 
After talking with ops, here is what we decided:

When an area selection is made, all the districts in that area will be selected
If one of the districts is deselected, the area selection will be removed
•	The area is on only when all of the districts are selected.
If the missing district is selected again, the area will be checked off
 
When an area is deselected, all districts within that area will be deselected
Each district can be select/deselected at any time independent of the area selection
•	When all the districts within an area are selected, the area will be selected
•	If any/all of the districts within an area are deselected, the area will be deselected
 
For example:
•	If LLD and KD are selected, no areas will be selected
•	If LLB is added, the N. East area will be selected
•	If SC is selected, no change to the area will occur
•	If SC and EST are selected, the S. East area will be selected
 
Eg. 2
•	LLD, LB, KD, SC and EST are all selected
•	Both S. East and N. East will be selected
•	If LLD is deselected, the N. East area will be deselected

**Comment by cameliabalan** [comment]
Tested in the Test environment in build #50 and passed, the area in filtering is working as described.

**Comment by JasonSchneider19** [comment]
Confirmed, working
