### ISSUE TITLE
eService Performance Change

### ISSUE THREAD

**Issue by awangatsanjel** [Sanjel-Energy-Services/eService_WorkItems#87]
## Customer Statement

I have been asked to see if we can split out “Late” incidents from Quality Incidents (in other words, a new primary incident type will need to be created for Lates, similar to Quality, MVI, Injury, etc.). Creating a new primary incident type in SCORE isn’t a big deal, we have created a few new ones over the past couple years. The issue in this case though, is that this new “Late” incident type, will need to be entered into eService the same way a Quality incident is entered and will need to import into SCORE as a “Late” primary incident, rather than a Quality incident. And if that’s possible, I would actually like to add a third primary incident type for “Quality – Well Integrity” which already exists in SCORE (I just manually change each one from a Quality incident to a Quality – Well Integrity incident).

 In addition to this, I would also like to see if we can add in dependent dropdown lists for the incident type, performance metric and severity fields; for example, only certain performance metric categories could be selected for certain incident types. I have already mapped out how these dependent dropdowns would look like (see attached).  Below is a breakdown of what I think would need to happen to make all of this work.

### eService Update

- Add new field in Job  Performance section for “Primary Incident” – Quality, Late, and Quality –     Well Integrity
- Create dependent drop  down lists for “Incident Type” depending on the “Primary Incident” (mapped     out in attached spreadsheet)
- Create dependent drop  down lists for “Actual Severity” depending on the “Primary Incident”     (mapped out in attached spreadsheet)
- Create dependent drop  down lists for “Performance Metric” depending on the “Incident Type”     category (mapped out in attached spreadsheet)
- Integrate such that     “Late” and “Quality – Well Integrity” incidents are imported from eService     into SCORE under those same primary incident types

### Screen Mock
![Performance Change](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/55812393/aeeeb451-8449-4083-b6e9-0c82280a921a)

### Master Data

[eService Job Performance Changes - 2023.xlsx](https://github.com/Sanjel-Energy-Services/eService_WorkItems/files/12581616/eService.Job.Performance.Changes.-.2023.xlsx)

**Comment by Alice0610** [comment]
@awangatsanjel  After review the requirement, I have below queries, can you provide confirmation?

1.  Add new field in Job Performance section for “Primary Incident” – Quality, Late, and Quality – Well Integrity
      Will Late and Quality-Well Integrity be stored under the dropdown list of Primary Incident?

2. My analysis of data integration is as below 
- Add Actual Severity  options of Late incidents  to the dropdown list of Actual Severity
- Add Actual Severity options of  Quality-Well Integrity to the dropdown list of Actual Severity
- Add Performance Metric options of Late incidnets to the dropdown list of  Performance Metric
- Add Performance Metric options of Quality-Well Integrity to the dropdown list of Performance Metric

3. If both Quality Incident and Quality-Well Integrity contains the same Incident Type, for example, Cement/Product Not Placed as Planned, do we need to delete the option from Incident Type dependent on Quality Incident? Or we can keep the same?

**Comment by awangatsanjel** [comment]
@Alice0610 I have broken down the tasks and make some fundamental changes. Please refer to the tickets created newly.

You don't need to do any further analysis anymore, just digest these ticket. Review the new tickets with developers, prepare test cases for testing.
