### ISSUE TITLE
DRB Building Crews in Crew Management

### ISSUE THREAD

**Issue by JasonSchneider19** [Sanjel-Energy-Services/eService_WorkItems#93]
There are a couple issues in the Crew Mgmt page:
When I build a crew in Crew Management its taking 15-30 minutes for that new crew to show up as an option for building load requests on the Rig Board

every time that I go to the Crew Mgmt page, the Planned/Not Planned bars show up as blanks and it takes several refreshes to populate them.  This happens whether its one district selected, multiple districts, one unit type, or multiple.  
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/8c4ad7e1-ad2f-4f1f-924a-02a8244c0f5d)

**Comment by arcurve-cheryl-chan** [comment]
@cameliabalan Can you please try to reproduce?

**Comment by arcurve-cheryl-chan** [comment]
Assigning to @awangatsanjel as per request to investigate in Rig Board.

**Comment by arcurve-cheryl-chan** [comment]
Ready to test in UAT.

**Comment by JasonSchneider19** [comment]
Confirmed - working
